version: "3.8"

services:
  php:
    image: k8s-demo-back-end-php:dev
    build:
      context: back-end
      dockerfile: docker/Dockerfile
      target: php-dev
  nginx:
    image: k8s-demo-back-end-nginx:dev
    build:
      context: back-end
      dockerfile: docker/Dockerfile
      target: nginx-dev
    ports:
      - 31000:80
    depends_on:
      - php
